@startuml ECサイト_統合ドメインモデル図_is_a追加
skinparam componentStyle rectangle
hide circle

' --- 主要な概念（エンティティ） ---
component [ユーザー]
component [商品]
component [注文]
component [配送]
component [注文明細]
component [カート]
component [決済]
component [返品_返金]

' --- is-a モデルの定義 ---
component [サイト管理者]
component [ステータス]


' --- 属性（詳細） ---
component [氏名]
component [メールアドレス]
component [住所]
component [郵便番号]
component [電話番号]
component [注文日時]
component [商品コード]
component [商品名]
component [価格_単価]
component [在庫数]
component [数量]
component [配達予定日]
component [配送先住所]
component [配達ステータス]
component [決済ログ詳細]


' --- is-a (継承) の表現 ---
' ユーザー is-a サイト管理者 (サイト管理者はユーザーの一種)
[ユーザー] <|-- [サイト管理者] : is-a

' ステータス is-a 決済ステータス/返金ステータス (具体的なステータスは一般的なステータスの一種)
[ステータス] <|-- [決済ステータス] : is-a
[ステータス] <|-- [返金ステータス] : is-a
[ステータス] <|-- [配達ステータス] : is-a


' --- 概念間の関連付け（ビジネス上の関係） ---
[ユーザー] -- [注文] : 注文する
[ユーザー] -- [カート] : 保持する
[ユーザー] -- [返品_返金] : 依頼する

[カート] -- [注文]

[注文] -- [注文明細] : 1対多
[注文明細] -- [商品] : 含む
[注文] -- [配送] : 配送される

[注文] -- [決済] : 決済情報
[注文] -- [返品_返金] : 関連づく

' 管理者と管理対象
[サイト管理者] -- [商品] : 管理する
[サイト管理者] -- [配送] : 配送依頼/管理
[サイト管理者] -- [返品_返金] : 対応する


' --- 概念と属性の関連付け（詳細情報） ---

[ユーザー] o-- [氏名]
[ユーザー] o-- [メールアドレス]
[ユーザー] o-- [住所]
[ユーザー] o-- [郵便番号]
[ユーザー] o-- [電話番号]

[注文] o-- [注文日時]

[商品] o-- [商品コード]
[商品] o-- [商品名]
[商品] o-- [価格_単価]
[商品] o-- [在庫数]

[注文明細] o-- [数量]

[配送] o-- [配達予定日]
[配送] o-- [配送先住所]
[配送] o-- [配達ステータス] 

[決済] o-- [決済ログ詳細]
[決済] o-- [決済ステータス] 

[返品_返金] o-- [返金ステータス] 

@enduml